Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: login
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: emailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: loginIndex
          KeySchema:
            - AttributeName: login
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.users.tableName}
  ContestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: contestId
          AttributeType: S
      KeySchema:
        - AttributeName: contestId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.contests.tableName}
  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ticketId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: userLogin
          AttributeType: S
      KeySchema:
        - AttributeName: ticketId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: userLoginIndex
          KeySchema:
            - AttributeName: userLogin
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.tickets.tableName}
